spring:
  application:
    name: springboot-upload-file-s3-api
  datasource:
    url: jdbc:postgresql://localhost:5432/upload_file
    username: postgres
    password: 291197
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    remote:
      secret: 123

cloud:
  aws:
    credentials:
      access-key: AKIAQ76Y4KSDP3Z7VTQ5
      secret-key: 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
    region: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: springboot-uploadfiles
