spring:
  application:
    name: springboot-upload-file-s3-api
  datasource:
    url: jdbc:postgresql://localhost:5432/upload_file
    username: postgres
    password: 291197
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8000

flyway:
  url: jdbc:postgresql://localhost:5432
  schemas: pocketmat
  user: postgres
  password: 291197
  baselineOnMigrate: true
  enabled: true

cloud:
  aws:
    credentials:
      access-key: AKIAQ76Y4KSDDREM6XG6
      secret-key: 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
    region: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: springboot-uploadfiles
